on: push

jobs:
  build-and-test:
    runs-on: ubuntu-latest  # You can change this to the runners you need
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: npm install
      - name: Build for deployment
        run: npm run build  # Adjust based on your build command
